const SDG_KEYWORDS = {

  //sdg 1 - NO POVERTY
  "SDG 1": [
    // English
    "poverty",
    "poor",
    "low income",
    "income",
    "livelihood",
    "indigent",
    "4ps",
    "social protection",
    "subsistence",
    "destitute",
    "welfare",
    "financial assistance",
    "cash assistance",
    "economic assistance",
    "poverty reduction",
    "poverty alleviation",
    "social assistance",
    "financial aid",
    "income support",
    "community assistance",
    "low-income families",
    "poor families",
    "disadvantaged families",
    "economic hardship",

    // Filipino
    "kahirapan",
    "mahirap",
    "pamilyang mahirap",
    "pamilyang kapos",
    "kapos sa pera",
    "kapos sa buhay",
    "mababang kita",
    "walang sapat na kita",
    "kita",
    "kabuhayan",
    "tulong pinansyal",
    "ayuda",
    "tulong pangkabuhayan",
    "tulong pinansiyal",
    "ayudang pinansyal",
    "ayudang pinansiyal",
    "suporta sa kita",
    "proteksyong panlipunan",
    "programang pangkabuhayan",
    "pagbawas ng kahirapan",
    "pag-alis sa kahirapan",
    "pagtulong sa mahihirap",
    "pamilyang nangangailangan",
    "mga nangangailangan",
    "walang sapat na pera",
    "walang kabuhayan",
    "walang kita",
    "mahirap na pamilya",
    "tulong sa mahihirap",
    "ayuda sa mahihirap",

    // Taglish / Philippine usage
    "livelihood program",
    "livelihood project",
    "livelihood assistance",
    "financial assistance program",
    "cash assistance program",
    "community livelihood",
    "poverty program",
    "anti-poverty",
    "anti poverty"
  ],


  //sdg 2 - ZERO HUNGER
  "SDG 2": [
    // English
    "hunger",
    "food",
    "nutrition",
    "agriculture",
    "farming",
    "farmer",
    "farmers",
    "malnutrition",
    "crops",
    "harvest",
    "feeding",
    "food security",
    "food insecurity",
    "vegetable garden",
    "community garden",
    "organic farming",
    "rice",
    "livestock",
    "fisheries",
    "farming technology",
    "agricultural development",
    "food assistance",
    "feeding program",
    "feeding program",
    "school feeding",
    "farm to market",
    "food production",
    "food distribution",
    "sustainable agriculture",

    // Filipino
    "gutom",
    "pagkagutom",
    "pagkain",
    "nutrisyon",
    "nutrisyon ng bata",
    "malnutrisyon",
    "agrikultura",
    "pagsasaka",
    "magsasaka",
    "sakahan",
    "pananim",
    "ani",
    "pag-aani",
    "pagkain para sa komunidad",
    "seguridad sa pagkain",
    "kakulangan sa pagkain",
    "hardin",
    "halamanan",
    "gulayan",
    "gulayan ng barangay",
    "pagtatanim ng gulay",
    "organikong pagsasaka",
    "pag-aalaga ng hayop",
    "pangingisda",
    "kabuhayang pang-agrikultura",
    "programang pagpapakain",
    "libreng pagkain",
    "pamamahagi ng pagkain",
    "suplay ng pagkain",
    "produksyon ng pagkain",
    "pagpapalago ng pananim",
    "tulong sa mga magsasaka",

    // Taglish
    "feeding program",
    "food assistance",
    "food distribution",
    "community garden",
    "urban farming",
    "agri program",
    "agriculture program",
    "farmers assistance",
    "farmer assistance",
    "nutrition program"
  ],


  //sdg 3 - GOOD HEALTH AND WELL-BEING
  "SDG 3": [
    // English
    "health",
    "healthcare",
    "medical",
    "hospital",
    "disease",
    "wellness",
    "clinic",
    "medicine",
    "medication",
    "vaccination",
    "maternal",
    "mental health",
    "covid",
    "pandemic",
    "immunization",
    "doctor",
    "nurse",
    "patient",
    "health center",
    "public health",
    "health services",
    "medical mission",
    "medical assistance",
    "first aid",
    "disease prevention",
    "health education",
    "maternal health",
    "child health",
    "infant health",
    "reproductive health",
    "nutrition health",
    "well-being",
    "wellbeing",
    "sanitation health",

    // Filipino
    "kalusugan",
    "pangkalusugan",
    "serbisyong pangkalusugan",
    "serbisyo sa kalusugan",
    "ospital",
    "doktor",
    "doctor",
    "nars",
    "klinika",
    "health center",
    "barangay health center",
    "gamot",
    "medisina",
    "bakuna",
    "pagbabakuna",
    "bakunahan",
    "sakit",
    "karamdaman",
    "pag-iwas sa sakit",
    "kalusugan ng ina",
    "kalusugan ng bata",
    "kalusugan ng sanggol",
    "kalusugan ng isip",
    "kalusugang pangkaisipan",
    "kalusugan ng komunidad",
    "misyon medikal",
    "libreng checkup",
    "libreng pagpapagamot",
    "medical mission",
    "tulong medikal",
    "serbisyong medikal",
    "unang lunas",
    "kalinisan",
    "kabutihang panlahat",
    "kapakanan",
    "kapakanan ng komunidad",

    // Taglish
    "health program",
    "health project",
    "medical mission",
    "medical assistance",
    "health checkup",
    "free checkup",
    "mental health program",
    "vaccination program",
    "health awareness",
    "health campaign",
    "barangay health program"
  ],


//sdg 4 - QUALITY EDUCATION
  "SDG 4": [
    // English
    "education",
    "school",
    "learning",
    "literacy",
    "students",
    "student",
    "teacher",
    "teachers",
    "classroom",
    "scholarship",
    "training",
    "skills",
    "education program",
    "educational program",
    "school supplies",
    "tutorial",
    "tutoring",
    "reading",
    "writing",
    "vocational",
    "technical education",
    "digital literacy",
    "education access",
    "inclusive education",
    "early childhood education",
    "higher education",
    "academic",
    "knowledge",
    "capacity building",

    // Filipino
    "edukasyon",
    "pag-aaral",
    "paaralan",
    "eskwelahan",
    "pagkatuto",
    "pag-aaral ng mga bata",
    "literasiya",
    "karunungan",
    "mag-aaral",
    "estudyante",
    "guro",
    "silid-aralan",
    "iskolar",
    "iskolarship",
    "tulong pang-edukasyon",
    "kagamitan sa paaralan",
    "school supplies",
    "pagtuturo",
    "pagsasanay",
    "kasanayan",
    "pagbabasa",
    "pagsulat",
    "tutorial",
    "libreng tutorial",
    "pagbibigay ng scholarship",
    "programang pang-edukasyon",
    "pagpapaunlad ng kaalaman",
    "pagpapaunlad ng kasanayan",
    "digital literacy",
    "pagkatuto ng kabataan",
    "edukasyon para sa lahat",
    "access sa edukasyon",

    // Taglish
    "education program",
    "educational assistance",
    "scholarship program",
    "school assistance",
    "student assistance",
    "learning program",
    "skills training",
    "training program",
    "digital literacy program"
  ],


  //sdg 5 - GENDER EQUALITY
  "SDG 5": [
    // English
    "gender",
    "women",
    "woman",
    "female",
    "girls",
    "girl",
    "equality",
    "empowerment",
    "gbv",
    "gender based violence",
    "gender-based violence",
    "discrimination",
    "violence against women",
    "violence against girls",
    "feminist",
    "women empowerment",
    "women rights",
    "gender equality",
    "equal rights",
    "sexual harassment",
    "domestic violence",
    "women leadership",
    "women participation",

    // Filipino
    "kasarian",
    "kababaihan",
    "babae",
    "mga babae",
    "batang babae",
    "pagkakapantay-pantay",
    "pantay na karapatan",
    "karapatan ng kababaihan",
    "pagpapalakas sa kababaihan",
    "empowerment ng kababaihan",
    "diskriminasyon",
    "karahasan laban sa kababaihan",
    "karahasan laban sa babae",
    "pang-aabuso sa babae",
    "pang-aabuso",
    "sexual harassment",
    "panghaharass",
    "pantay na oportunidad",
    "pagkakapantay ng kasarian",
    "partisipasyon ng kababaihan",
    "liderato ng kababaihan",
    "karapatan ng babae",

    // Taglish
    "women empowerment",
    "gender equality program",
    "women rights",
    "women leadership",
    "gender awareness",
    "gender program",
    "women participation"
  ],


  //sdg 6 - CLEAN WATER AND SANITATION
  "SDG 6": [
    // English
    "water",
    "clean water",
    "drinking water",
    "potable water",
    "sanitation",
    "sewage",
    "sewer",
    "drainage",
    "toilet",
    "toilets",
    "hygiene",
    "watershed",
    "irrigation",
    "water supply",
    "water system",
    "water treatment",
    "wastewater",
    "water quality",
    "water conservation",
    "water pollution",
    "rainwater",
    "water access",
    "sanitary",
    "cleanliness",

    // Filipino
    "tubig",
    "malinis na tubig",
    "inuming tubig",
    "ligtas na inuming tubig",
    "malinis na inumin",
    "sanitasyon",
    "kalinisan",
    "palikuran",
    "banyo",
    "impeksyon",
    "kanal",
    "drainage",
    "imburnal",
    "sistema ng tubig",
    "suplay ng tubig",
    "suplay ng malinis na tubig",
    "paglilinis ng tubig",
    "paggamot ng tubig",
    "maruming tubig",
    "basurang tubig",
    "pangangalaga sa tubig",
    "pagtitipid ng tubig",
    "polusyon sa tubig",
    "kalidad ng tubig",
    "irigasyon",
    "patubig",
    "palikuran sa komunidad",
    "kalinisan ng kapaligiran",

    // Taglish
    "water system",
    "water project",
    "water supply project",
    "clean water project",
    "sanitation program",
    "hygiene program",
    "water conservation",
    "water treatment"
  ],


  //sdg 7 - AFFORDABLE AND CLEAN ENERGY
  "SDG 7": [
    // English
    "energy",
    "electricity",
    "solar",
    "solar power",
    "renewable energy",
    "renewable",
    "power",
    "generator",
    "fuel",
    "biomass",
    "wind",
    "wind energy",
    "electrification",
    "clean energy",
    "hydropower",
    "hydroelectric",
    "geothermal",
    "energy efficiency",
    "energy conservation",
    "solar panel",
    "solar panels",
    "off grid",
    "off-grid",

    // Filipino
    "enerhiya",
    "kuryente",
    "elektrisidad",
    "enerhiyang malinis",
    "enerhiyang nababago",
    "renewable energy",
    "enerhiyang solar",
    "lakas ng araw",
    "araw na enerhiya",
    "solar panel",
    "turbina",
    "hangin",
    "enerhiya mula sa hangin",
    "biomass",
    "enerhiyang tubig",
    "enerhiya ng tubig",
    "geothermal",
    "pagtitipid ng enerhiya",
    "kahusayan sa enerhiya",
    "pagkakabit ng kuryente",
    "pagbibigay ng kuryente",

    // Taglish
    "solar project",
    "solar energy project",
    "renewable energy project",
    "clean energy project",
    "solar panel project",
    "electrification project",
    "energy efficiency program"
  ],


//sdg 8 - DECENT WORK AND ECONOMIC GROWTH
  "SDG 8": [
    // English
    "employment",
    "jobs",
    "job",
    "livelihood",
    "economy",
    "economic growth",
    "business",
    "entrepreneurship",
    "entrepreneur",
    "skills training",
    "work",
    "labor",
    "labour",
    "income generation",
    "workforce",
    "workers",
    "employment opportunities",
    "job opportunities",
    "decent work",
    "small business",
    "micro business",
    "startup",
    "enterprise",
    "vocational training",
    "career development",
    "job creation",
    "local economy",
    "financial literacy",

    // Filipino
    "trabaho",
    "empleyo",
    "hanapbuhay",
    "kabuhayan",
    "pagkakakitaan",
    "kita",
    "negosyo",
    "maliit na negosyo",
    "entrepreneurship",
    "pagnenegosyo",
    "manggagawa",
    "paggawa",
    "karapatan ng manggagawa",
    "oportunidad sa trabaho",
    "paglikha ng trabaho",
    "pag-unlad ng ekonomiya",
    "ekonomiya",
    "pagsasanay sa trabaho",
    "pagsasanay sa kasanayan",
    "kasanayan sa trabaho",
    "hanapbuhay para sa kabataan",
    "kabuhayan ng pamilya",
    "pagpapaunlad ng kabuhayan",
    "pagnenegosyo",
    "tulong sa negosyo",
    "micro negosyo",
    "maliliit na negosyo",

    // Taglish
    "job training",
    "job creation",
    "employment program",
    "livelihood program",
    "livelihood training",
    "business training",
    "entrepreneurship program",
    "skills training program",
    "small business program"
  ],


  //sdg 9 - INDUSTRY, INNOVATION AND INFRASTRUCTURE
  "SDG 9": [
    // English
    "infrastructure",
    "road",
    "roads",
    "bridge",
    "bridges",
    "technology",
    "innovation",
    "internet",
    "connectivity",
    "industry",
    "construction",
    "digital",
    "digital technology",
    "telecommunication",
    "transport infrastructure",
    "public infrastructure",
    "research",
    "development",
    "engineering",
    "manufacturing",
    "industrialization",
    "broadband",
    "digital infrastructure",
    "innovation hub",

    // Filipino
    "imprastraktura",
    "imprastruktura",
    "kalsada",
    "daan",
    "tulay",
    "teknolohiya",
    "makabagong teknolohiya",
    "inobasyon",
    "internet",
    "koneksyon",
    "industriya",
    "konstruksyon",
    "digital",
    "komunikasyon",
    "telekomunikasyon",
    "pananaliksik",
    "pagpapaunlad",
    "pabrika",
    "manufacturing",
    "broadband",
    "digital na imprastraktura",
    "imprastraktura ng komunidad",
    "pagpapaunlad ng teknolohiya",

    // Taglish
    "technology project",
    "innovation project",
    "infrastructure project",
    "road project",
    "bridge project",
    "internet access",
    "internet connectivity",
    "digital transformation",
    "digital project"
  ],


  //sdg 10 - REDUCED INEQUALITIES
  "SDG 10": [
    // English
    "inequality",
    "inequalities",
    "inclusion",
    "inclusive",
    "marginalized",
    "marginalised",
    "disability",
    "disabled",
    "indigenous",
    "indigenous peoples",
    "discrimination",
    "social",
    "equity",
    "vulnerable",
    "persons with disability",
    "pwd",
    "equal opportunity",
    "social inclusion",
    "equal access",
    "human rights",
    "minority",
    "minorities",
    "social justice",

    // Filipino
    "hindi pagkakapantay-pantay",
    "hindi pagkakapantay",
    "pagkakapantay-pantay",
    "inklusyon",
    "pantay na oportunidad",
    "pantay na access",
    "diskriminasyon",
    "marginalisado",
    "mga katutubo",
    "katutubo",
    "taong may kapansanan",
    "may kapansanan",
    "pwd",
    "mahihinang sektor",
    "sektor na nangangailangan",
    "mahihina",
    "pantay na karapatan",
    "karapatang pantao",
    "panlipunang katarungan",
    "pantay na serbisyo",
    "pantay na oportunidad",

    // Taglish
    "PWD assistance",
    "PWD program",
    "inclusive program",
    "inclusion program",
    "social inclusion",
    "equal opportunity program",
    "indigenous peoples program"
  ],


  //sdg 11 - SUSTAINABLE CITIES AND COMMUNITIES
  "SDG 11": [
    // English
    "urban",
    "community",
    "housing",
    "city",
    "cities",
    "barangay",
    "sustainable",
    "transport",
    "public transport",
    "public space",
    "slum",
    "informal settlers",
    "urban planning",
    "housing program",
    "community development",
    "disaster resilient community",
    "resilient city",
    "safe community",
    "affordable housing",
    "public facilities",
    "community facilities",
    "walkability",
    "traffic",
    "mobility",

    // Filipino
    "lungsod",
    "siyudad",
    "komunidad",
    "barangay",
    "pamayanan",
    "kabahayan",
    "pabahay",
    "murang pabahay",
    "abot-kayang pabahay",
    "transportasyon",
    "pampublikong transportasyon",
    "pampublikong lugar",
    "ligtas na komunidad",
    "matatag na komunidad",
    "maunlad na komunidad",
    "pagpapaunlad ng komunidad",
    "pagpaplano ng lungsod",
    "pabahay para sa mahihirap",
    "mga informal settler",
    "trapiko",
    "paglalakad",
    "mobilidad",
    "pasilidad ng komunidad",

    // Taglish
    "community development",
    "housing project",
    "housing program",
    "barangay development",
    "urban development",
    "public transportation",
    "community project",
    "sustainable community",
    "disaster resilient community"
  ],


  //sdg 12 - RESPONSIBLE CONSUMPTION AND PRODUCTION
  "SDG 12": [
    // English
    "waste",
    "waste management",
    "recycling",
    "consumption",
    "production",
    "garbage",
    "segregation",
    "zero waste",
    "sustainable consumption",
    "materials",
    "plastic",
    "plastic waste",
    "reuse",
    "reduce",
    "recycle",
    "compost",
    "composting",
    "biodegradable",
    "environmentally friendly",
    "eco friendly",
    "circular economy",
    "responsible consumption",
    "responsible production",
    "solid waste",
    "waste reduction",

    // Filipino
    "basura",
    "pamamahala ng basura",
    "paghihiwalay ng basura",
    "segregasyon",
    "recycling",
    "pagre-recycle",
    "pagbawas ng basura",
    "zero waste",
    "pag-reuse",
    "muling paggamit",
    "pagbawas",
    "pagrecycle",
    "pagko-compost",
    "nabubulok",
    "di-nabubulok",
    "plastik",
    "basurang plastik",
    "pagkonsumo",
    "produksyon",
    "paggawa ng produkto",
    "matipid na pagkonsumo",
    "responsableng pagkonsumo",
    "responsableng produksyon",
    "pangangalaga ng materyales",
    "kalinisan ng komunidad",

    // Taglish
    "waste management program",
    "waste segregation",
    "recycling program",
    "zero waste program",
    "plastic reduction",
    "plastic waste",
    "composting program",
    "solid waste management"
  ],


  //sdg 13 - CLIMATE ACTION
  "SDG 13": [
    // English
    "climate",
    "climate change",
    "environment",
    "environmental",
    "flooding",
    "flood",
    "disaster",
    "disaster risk",
    "typhoon",
    "storm",
    "resilience",
    "carbon",
    "carbon emissions",
    "greenhouse gas",
    "greenhouse gases",
    "adaptation",
    "mitigation",
    "global warming",
    "extreme weather",
    "climate resilience",
    "disaster preparedness",
    "disaster response",
    "emergency preparedness",
    "climate action",

    // Filipino
    "klima",
    "pagbabago ng klima",
    "climate change",
    "kapaligiran",
    "pangangalaga sa kapaligiran",
    "pagbaha",
    "baha",
    "bagyo",
    "sakuna",
    "paghahanda sa sakuna",
    "katatagan",
    "resilience",
    "emisyon ng carbon",
    "carbon",
    "global warming",
    "pag-init ng mundo",
    "pagbabago ng panahon",
    "matinding panahon",
    "pag-angkop",
    "mitigasyon",
    "pagbawas ng carbon",
    "paghahanda sa bagyo",
    "paghahanda sa baha",
    "pagtugon sa sakuna",
    "pagkilos para sa klima",

    // Taglish
    "climate action",
    "climate program",
    "climate project",
    "disaster preparedness",
    "disaster risk reduction",
    "disaster risk management",
    "environmental project",
    "climate resilience"
  ],


  //sdg 14 - LIFE BELOW WATER
  "SDG 14": [
    // English
    "ocean",
    "oceans",
    "marine",
    "marine life",
    "fish",
    "fishing",
    "coastal",
    "coast",
    "sea",
    "coral",
    "coral reef",
    "mangrove",
    "aquatic",
    "water pollution",
    "marine pollution",
    "ocean pollution",
    "marine ecosystem",
    "fisheries",
    "sustainable fishing",
    "overfishing",
    "sea turtle",
    "ocean conservation",
    "coastal conservation",

    // Filipino
    "karagatan",
    "dagat",
    "buhay-dagat",
    "yamang dagat",
    "lamang-dagat",
    "isda",
    "pangingisda",
    "mangingisda",
    "baybayin",
    "baybaying-dagat",
    "coral",
    "bahura",
    "bakawan",
    "mangrove",
    "hayop sa dagat",
    "polusyon sa dagat",
    "polusyon sa karagatan",
    "pangangalaga sa dagat",
    "pangangalaga sa karagatan",
    "pangangalaga sa baybayin",
    "pangisdaan",
    "sobrang pangingisda",
    "pagpapanatili ng yamang dagat",
    "pagprotekta sa karagatan",

    // Taglish
    "marine conservation",
    "ocean conservation",
    "coastal cleanup",
    "coastal protection",
    "marine protection",
    "fisheries program",
    "fishing community",
    "mangrove planting",
    "coral reef protection"
  ],


  //sdg 15 - LIFE ON LAND
  "SDG 15": [
    // English
    "forest",
    "forests",
    "land",
    "biodiversity",
    "wildlife",
    "ecosystem",
    "trees",
    "tree planting",
    "deforestation",
    "soil",
    "animals",
    "planting",
    "reforestation",
    "afforestation",
    "forest conservation",
    "wildlife conservation",
    "habitat",
    "natural resources",
    "land degradation",
    "soil conservation",
    "protected area",
    "endangered species",
    "native species",

    // Filipino
    "gubat",
    "kagubatan",
    "lupa",
    "biodiversity",
    "likas na yaman",
    "mga hayop",
    "mga halaman",
    "puno",
    "pagtatanim ng puno",
    "pagtatanim",
    "pagkakalbo ng kagubatan",
    "pangangalaga ng gubat",
    "pangangalaga sa kagubatan",
    "reforestation",
    "pagpapanumbalik ng kagubatan",
    "pangangalaga sa hayop",
    "wildlife",
    "tirahan ng mga hayop",
    "ecosystem",
    "kalikasan",
    "pangangalaga sa kalikasan",
    "pangangalaga ng lupa",
    "pagkasira ng lupa",
    "mga endangered species",
    "protektadong lugar",
    "pook pangkalikasan",

    // Taglish
    "tree planting program",
    "tree planting project",
    "forest conservation",
    "wildlife conservation",
    "environmental conservation",
    "reforestation project",
    "biodiversity program",
    "habitat protection"
  ],


  //SDG 16 - PEACE, JUSTICE AND STRONG INSTITUTIONS
  "SDG 16": [
    // English
    "peace",
    "justice",
    "governance",
    "law",
    "laws",
    "corruption",
    "transparency",
    "accountability",
    "institutions",
    "crime",
    "security",
    "conflict",
    "human rights",
    "legal assistance",
    "public service",
    "good governance",
    "citizen participation",
    "access to justice",
    "rule of law",
    "anti-corruption",
    "community safety",
    "peacebuilding",
    "mediation",
    "democracy",
    "election",
    "civic participation",

    // Filipino
    "kapayapaan",
    "katarungan",
    "pamahalaan",
    "pamamahala",
    "mabuting pamamahala",
    "batas",
    "korapsyon",
    "laban sa korapsyon",
    "transparency",
    "pananagutan",
    "institusyon",
    "krimen",
    "seguridad",
    "siguridad",
    "salungatan",
    "karapatang pantao",
    "tulong legal",
    "serbisyong pampubliko",
    "kaligtasan ng komunidad",
    "pakikilahok ng mamamayan",
    "partisipasyon ng mamamayan",
    "access sa katarungan",
    "pangingibabaw ng batas",
    "pagpapatupad ng batas",
    "pagpapanatili ng kapayapaan",
    "pagresolba ng alitan",
    "pamamagitan",
    "demokrasya",

    // Taglish
    "good governance",
    "peace program",
    "peacebuilding program",
    "legal assistance",
    "anti-corruption program",
    "community safety",
    "public service program",
    "citizen participation"
  ],


  //SDG 17 - PARTNERSHIPS FOR THE GOALS
  "SDG 17": [
    // English
    "partnership",
    "partnerships",
    "cooperation",
    "international",
    "funding",
    "collaboration",
    "stakeholders",
    "ngo",
    "non-government organization",
    "development",
    "global",
    "aid",
    "donor",
    "government partnership",
    "public private partnership",
    "network",
    "coalition",
    "joint project",
    "joint program",
    "community partnership",
    "multi stakeholder",
    "resource mobilization",
    "capacity building",
    "technical assistance",

    // Filipino
    "pakikipagtulungan",
    "pagtutulungan",
    "pakikipag-ugnayan",
    "ugnayan",
    "pakikipagsosyo",
    "pakikipagtambalan",
    "pakikipagtulungan sa komunidad",
    "kasosyo",
    "mga katuwang",
    "stakeholder",
    "mga stakeholder",
    "organisasyon",
    "non-government organization",
    "samahan",
    "pondo",
    "pagpopondo",
    "tulong",
    "donasyon",
    "tulong pinansyal",
    "suporta",
    "pamahalaan",
    "pribadong sektor",
    "kooperasyon",
    "pandaigdigan",
    "pagpapaunlad",
    "pinagsamang proyekto",
    "pinagsamang programa",
    "pagbabahagi ng resources",
    "pagpapakilos ng resources",

    // Taglish
    "partnership program",
    "community partnership",
    "government partnership",
    "public private partnership",
    "stakeholder collaboration",
    "ngo partnership",
    "joint project",
    "joint program",
    "multi stakeholder partnership",
    "development partnership"
  ],

};

module.exports = SDG_KEYWORDS;